### ISSUE TITLE
origami-0.0.1 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [nedervold/origami#3]
According to http://hydra.cryp.to/build/537626/nixlog/2/raw, the module `Data.OrigamiTests` seems to be missing from the release tarball.

**Comment by nedervold** [comment]
Oops.  Newbie mistake; I got caught by this: http://stackoverflow.com/questions/4639526/why-does-cabal-sdist-not-include-all-files-needed-to-build

Thanks for catching the bug.

**Comment by nedervold** [comment]
Fixed in v0.0.2.
